apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: tickets
          image: gsdatabase/payments
          env:
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: STRIPE_SECRET_KEY
              value: sk_test_51LRhLTBlFmnLdwGWiAMjQ9lY3WdUYRHlbdrKhqEoWaJp4bkJ2UGKn53hmD5QScUv5irPEmbmttczxmEhaK3yoAX800EBgWdQby
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: MONGO_URI
              value: "mongodb://payments-mongo-srv:27017/payments"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
